prebuild script

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,10 +1,34 @@
 #!/usr/bin/env bash
 
-# fail fast
 set -e
 
-BP_DIR=$(cd $(dirname $0)/..; pwd) # absolute path
-BIN_DIR=$BP_DIR/bin
+BUILD_DIR=$1
+CACHE_DIR=$2
+ENV_DIR=$3
 
-python $BIN_DIR/compile.py "$@"
+
+
+if [ ! -f "$ENV_DIR/PROJECT_DIR" ]; then
+    echo "       PROJECT_DIR was not set. Aborting"
+    exit 1
+fi
+
+PROJECT_DIR="$(cat $ENV_DIR/PROJECT_DIR)"
+
+if [ ! -f "$BUILD_DIR/$PROJECT_DIR/prebuild" ]; then
+    echo "       prebuild script is not found. Aborting"
+    exit 1
+fi
+
+echo "       running prebuild"
+# move files to staging dir
+mkdir $BUILD_DIR/.staging
+shopt -s extglob
+mv $BUILD_DIR/!(.staging) $BUILD_DIR/.staging
+
+# run prebuild
+. "$BUILD_DIR/.staging/$PROJECT_DIR/prebuild" $BUILD_DIR/.staging $BUILD_DIR
+
+# delete staging dir
+rm -rf $BUILD_DIR/.staging
 
